name: Hello world workflow

on:
  push:
    branches: -main
  pull_request:
    branches: -main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello world
        run: echo "Hello world"
        shell: bash

  goodbye:
    runs-on: ubunto-latest
    steps:
      - name: Goodbye world
        run: echo "Goodbye world"
        shell: bash
